theme: jekyll-theme-slate
github: [metadata]
title: ownCloud Quickstart Guide
description: Installing and connecting with ownCloud
product-name: ownCloud
note: '<i class="fa fa-pencil"></i>'
warning: '<i class="fa fa-warning"></i> <b>Tip: </b>'
baseurl: /docs
